In [1]:
import numpy as np
import pandas as pd
import os

In [30]:
# Parser database to files

counter = 0
directory = "D://UT//algorithms//project//"
for filename in os.listdir(directory):
    counter += 1
    fp = open(directory + str(counter) + ".txt", "w")
    with open(directory + filename, 'r') as f:
        for line in f:
            if not ("[" in line or len(line) < 3):
                fp.write(line)
        fp.close()

In [31]:
# Parser file to array

def convert_to_game(s):
    moves = []
    s = s.split("\n")
    for line in s:
        line = line.split(" ")
        for l in line:
            l = l.split(".")
            if len(l) == 1:
                if l[0] not in ["1-0", "0-1", "1/2-1/2"]:
                    if len(l[0]) > 0:
                        moves.append(l[0])
            else:
                if len(l[1]) > 0:
                    moves.append(l[1])
    return moves

parties = []
directory = "D://UT//algorithms//project//"
for filename in [str(k) + ".txt" for k in np.arange(1, counter + 1)]:
    if filename == '1.txt':
        with open(directory + filename, 'r') as f:
            s = ""
            for line in f:
                if line[:2] == "1.":
                    if s:
                        parties.append(convert_to_game(s))
                    s = line
                else:
                    s += line


In [22]:
print(parties[0])

['c4', 'g6', 'd4', 'Nf6', 'Nc3', 'd5', 'cxd5', 'Nxd5', 'e4', 'Nxc3', 'bxc3', 'Bg7', 'Nf3', 'c5', 'Be3', 'Qa5', 'Qd2', 'O-O', 'Rc1', 'Nd7', 'Bd3', 'e5', 'd5', 'b5', 'O-O', 'c4', 'Bb1', 'Qa3', 'Bh6', 'Qd6', 'Bxg7', 'Kxg7', 'Nh4', 'f6', 'Bc2', 'a5', 'Qe3', 'Rf7', 'Bd1', 'Nc5', 'Be2', 'Bd7', 'g3', 'Re8', 'Rfe1', 'Nb7', 'Rb1', 'Qc5', 'Qd2', 'Nd6', 'Bf1', 'Rb8', 'Kh1', 'b4', 'Qe2', 'Rff8', 'Rec1', 'b3', 'Bg2', 'Qa3', 'axb3', 'cxb3', 'c4', 'Qc5', 'f4', 'a4', 'Qd3', 'Rfe8', 'f5', 'Rb4', 'Bf1', 'Reb8', 'fxg6', 'hxg6', 'Nf3', 'a3', 'Re1', 'Rxc4']


In [2]:
import numpy as np

figure = dict()
figure['Black Knight1'] = 12
figure['White Knight1'] = 2
figure['Black Knight2'] = 12
figure['White Knight2'] = 2
figure['Black Bishop'] = 14
figure['White Bishop'] = 4
figure['Black Rock1'] = 15
figure['White Rock1'] = 5
figure['Black Rock2'] = 15
figure['White Rock2'] = 5
figure['Black Pawn'] = 11
figure['White Pawn'] = 1
figure['Black King'] = 19
figure['White King'] = 9
figure['Black Queen'] = 18
figure['White Queen'] = 8

letter = dict()
letter['a'] = 0
letter['b'] = 1
letter['c'] = 2
letter['d'] = 3
letter['e'] = 4
letter['f'] = 5
letter['g'] = 6
letter['h'] = 7

figure_letter = dict()
figure_letter['N'] = 'Knight'
figure_letter['K'] = 'King'
figure_letter['R'] = 'Rock'
figure_letter['Q'] = 'Queen'
figure_letter['B'] = 'Bishop'

In [9]:
def initialize_board():
    board = np.zeros((8, 8))
    for i in range(8):
        board[i][1] = figure['White Pawn']
        board[i][6] = figure['Black Pawn']
    board[0][0] = figure['White Rock1']
    board[7][0] = figure['White Rock2']
    board[0][7] = figure['Black Rock1']
    board[7][7] = figure['Black Rock2']
    board[1][0] = figure['White Knight1']
    board[6][0] = figure['White Knight2']
    board[1][7] = figure['Black Knight1']
    board[6][7] = figure['Black Knight2']
    board[2][0] = figure['White Bishop']
    board[5][0] = figure['White Bishop']
    board[2][7] = figure['Black Bishop']
    board[5][7] = figure['Black Bishop']
    board[3][0] = figure['White Queen']
    board[4][0] = figure['White King']
    board[3][7] = figure['Black Queen']
    board[4][7] = figure['Black King']
    return board

board = initialize_board()
print(board)

[[  5.   1.   0.   0.   0.   0.  11.  15.]
 [  2.   1.   0.   0.   0.   0.  11.  12.]
 [  4.   1.   0.   0.   0.   0.  11.  14.]
 [  8.   1.   0.   0.   0.   0.  11.  18.]
 [  9.   1.   0.   0.   0.   0.  11.  19.]
 [  4.   1.   0.   0.   0.   0.  11.  14.]
 [  2.   1.   0.   0.   0.   0.  11.  12.]
 [  5.   1.   0.   0.   0.   0.  11.  15.]]


In [48]:
def perform_move(move, Player, board):
    if True: # move in possible_move
        if move[0] in ['N', 'R', 'K', 'B', 'Q']:
            if move[0] == 'K':
                # King move
                if 'x' not in move:
                    i = letter[move[1]]
                    j = int(move[2]) - 1
                else: # King shot
                    i = letter[move[2]]
                    j = int(move[3]) - 1
                for i1 in [-1, 0, 1]:
                    for j1 in [-1, 0, 1]:
                        if board[min(7, max(0, i + i1))][min(7, max(0, j + j1))] == 10 * Player + 9:
                            board[min(7, max(0, i + i1))][min(7, max(0, j + j1))] = 0
                board[i][j] = 10 * Player + 9
            else:
                # Rock move
                if move[0] == 'R':
                    if 'x' not in move:
                        # Need to add if two rocks on one vertical
                        if move[2] >= 'a' and move[2] <= 'h':
                            i = letter[move[2]]
                            j = int(move[3]) - 1
                            k = letter[move[1]]
                            board[k][j] = 0
                            board[i][j] = 10 * Player + 5
                        else:
                            i = letter[move[1]]
                            j = int(move[2]) - 1
                            for i1 in range(8):
                                if board[i][i1] == 10 * Player + 5:
                                    board[i][i1] = 0
                                    break
                                if board[i1][j] == 10 * Player + 5:
                                    board[i1][j] = 10 * Player + 5
                                    break
                    else:
                        if move[2] >= 'a' and move[2] <= 'h':
                            i = letter[move[2]]
                            j = int(move[3]) - 1
                            k = letter[move[1]]
                            board[k][j] = 0
                            board[i][j] = 10 * Player + 5
                        else:
                            i = letter[move[1]]
                            j = int(move[2]) - 1
                            for i1 in range(8):
                                if board[i][i1] == 10 * Player + 5:
                                    board[i][i1] = 0
                                    break
                                if board[i1][j] == 10 * Player + 5:
                                    board[i1][j] = 10 * Player + 5
                                    break
                else:
                    # Bishop move
                    if move[0] == 'B':
                        add = int('x' in move)
                        i = letter[move[1 + add]]
                        j = int(move[2 + add]) - 1
                        mod = (i + j) % 2
                        for i1 in range(8):
                            for j1 in range(8):
                                if (i1 + j1) % 2 == mod and board[i1][j1] == 10 * Player + 4:
                                    board[i1][j1] = 0
                                    break
                        board[i][j] = 10 * Player + 4
                    else:
                        if move[0] == 'N':
                            add = int('x' in move)
                            i = letter[move[1 + add]]
                            j = int(move[2 + add]) - 1
                            if move[2 + add] >= 'a' and move[2 + add] <= 'h':
                                print("OK")
                            else:
                                for i1 in range(8):
                                    for j1 in range(8):
                                        if abs(i - i1) * abs(j - j1) == 2 and board[i1][j1] == 10 * Player + 2:
                                            board[i1][j1] = 0
                                            break
                                board[i][j] = 10 * Player + 2
                        else:
                            if move[0] == 'Q':
                                add = int('x' in move)
                                i = letter[move[1 + add]]
                                j = int(move[2 + add]) - 1
                                for i1 in range(8):
                                    for j1 in range(8):
                                        if board[i1][j1] == 10 * Player + 8:
                                            board[i1][j1] = 0
                                            break
                                board[i][j] = 10 * Player + 8
        else:
            # Pawn move
            if move[0] in ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h']:
                if 'x' not in move:
                    m = int(move[1]) - 1
                    board[letter[move[0]]][m] = 10 * Player + 1
                    if Player == 0:
                        if board[letter[move[0]]][m - 2] == 10 * Player + 1 and not board[letter[move[0]]][m - 1] == 10 * Player + 1:
                            board[letter[move[0]]][m - 2] = 0
                        else:
                            board[letter[move[0]]][m - 1] = 0
                    else:
                        if board[letter[move[0]]][m + 2] == 10 * Player + 1 and not board[letter[move[0]]][m + 1] == 10 * Player + 1:
                                board[letter[move[0]]][m + 2] = 0
                        else:
                                board[letter[move[0]]][m + 1] = 0
                else:
                    new_v = int(move[3]) - 1
                    new_h = letter[move[2]]
                    old_h = letter[move[0]]
                    board[new_h][new_v] = 10 * Player + 1
                    board[old_h][new_v - 1 + 2 * Player] = 0
            else:
                if move[0] == '0':
                    # Short (two zeros)
                    if len(move) < 5:
                        i = 7 * Player
                        board[7][i] = 0 # Rock
                        board[4][i] = 0 # King
                        board[5][i] = 10 * Player + 5 # Rock
                        board[6][i] = 10 * Player + 9 # King
                    # Long
                    else:
                        i = 7 * Player
                        board[0][i] = 0 # Rock
                        board[4][i] = 0 # King
                        board[3][i] = 10 * Player + 5 # Rock
                        board[2][i] = 10 * Player + 9 # King
    return board
                    
board = initialize_board()
board = perform_move("e4", 0, board)
board = perform_move("e5", 1, board)
print(board)

[[  5.   1.   0.   0.   0.   0.  11.  15.]
 [  2.   1.   0.   0.   0.   0.  11.  12.]
 [  4.   1.   0.   0.   0.   0.  11.  14.]
 [  8.   1.   0.   0.   0.   0.  11.  18.]
 [  9.   0.   0.   1.  11.   0.   0.  19.]
 [  4.   1.   0.   0.   0.   0.  11.  14.]
 [  2.   1.   0.   0.   0.   0.  11.  12.]
 [  5.   1.   0.   0.   0.   0.  11.  15.]]


In [28]:
board = initialize_board()
board = perform_move("e4", 0, board)
board = perform_move("e5", 1, board)
board = perform_move("Bc4", 0, board)
#print(board)
board = perform_move("Bc5", 1, board)
#print(board)
board = perform_move("0-0", 0, board)
# print(board)
board = perform_move("0-0-0", 1, board)
print(board)

[[  5.   1.   0.   0.   0.   0.  11.   0.]
 [  2.   1.   0.   0.   0.   0.  11.  12.]
 [  4.   1.   0.   4.  14.   0.  11.  19.]
 [  8.   1.   0.   0.   0.   0.  11.  15.]
 [  0.   0.   0.   1.  11.   0.   0.   0.]
 [  5.   1.   0.   0.   0.   0.  11.   0.]
 [  9.   1.   0.   0.   0.   0.  11.  12.]
 [  0.   1.   0.   0.   0.   0.  11.  15.]]


In [32]:
play = parties[0]
print(play)

['Nf3', 'Nf6', 'c4', 'b6', 'b3', 'e6', 'Bb2', 'Bb7', 'e3', 'd5', 'Be2', 'dxc4', 'bxc4']


In [50]:
board = initialize_board()
board = perform_move(play[0], 0, board)
print(board)

[[  5.   1.   0.   0.   0.   0.  11.  15.]
 [  2.   1.   0.   0.   0.   0.  11.  12.]
 [  4.   1.   0.   0.   0.   0.  11.  14.]
 [  8.   1.   0.   0.   0.   0.  11.  18.]
 [  9.   1.   0.   0.   0.   0.  11.  19.]
 [  4.   1.   2.   0.   0.   0.  11.  14.]
 [  0.   1.   0.   0.   0.   0.  11.  12.]
 [  5.   1.   0.   0.   0.   0.  11.  15.]]


In [51]:
for i in range(1, 11):
    board = perform_move(play[i], i % 2, board)
print(board)

[[  5.   1.   0.   0.   0.   0.  11.  15.]
 [  2.   4.   1.   0.   0.  11.  14.  12.]
 [  0.   0.   0.   1.   0.   0.  11.   0.]
 [  8.   1.   0.   0.  11.   0.   0.  18.]
 [  9.   4.   1.   0.   0.  11.   0.  19.]
 [  0.   1.   2.   0.   0.  12.  11.  14.]
 [  0.   1.   0.   0.   0.   0.  11.   0.]
 [  5.   1.   0.   0.   0.   0.  11.  15.]]


In [52]:
board = perform_move(play[11], 1, board)
print(board)

[[  5.   1.   0.   0.   0.   0.  11.  15.]
 [  2.   4.   1.   0.   0.  11.  14.  12.]
 [  0.   0.   0.  11.   0.   0.  11.   0.]
 [  8.   1.   0.   0.   0.   0.   0.  18.]
 [  9.   4.   1.   0.   0.  11.   0.  19.]
 [  0.   1.   2.   0.   0.  12.  11.  14.]
 [  0.   1.   0.   0.   0.   0.  11.   0.]
 [  5.   1.   0.   0.   0.   0.  11.  15.]]
